(TeX-add-style-hook "alter"
 (lambda ()
    (LaTeX-add-labels
     "sec-1"
     "sec-2"
     "sec-2-1"
     "sec-2-2")
    (TeX-run-style-hooks
     "hyperref"
     "amssymb"
     "wasysym"
     "marvosym"
     "textcomp"
     "amsmath"
     "ulem"
     "normalem"
     "rotating"
     "wrapfig"
     "float"
     "longtable"
     "graphicx"
     "fixltx2e"
     "fontenc"
     "T1"
     "inputenc"
     "utf8"
     "geometry"
     "bottom=3truecm"
     "top=3truecm"
     "right=2truecm"
     "left=2truecm"
     "luatexja-preset"
     "kozuka-pr6n"
     "latex2e"
     "ltjsarticle10"
     "ltjsarticle"
     "")))

